# Generated by Django 2.2.7 on 2019-12-31 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='GetUserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Roles', verbose_name='RoleID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=222, null=True, verbose_name='Name')),
                ('surname', models.CharField(max_length=222, null=True, verbose_name='Surname')),
                ('login', models.CharField(max_length=222, unique=True, verbose_name='Login')),
                ('password', models.CharField(max_length=222, verbose_name='Password')),
                ('email', models.EmailField(db_index=True, max_length=50, unique=True)),
                ('phone', models.CharField(max_length=222, null=True, verbose_name='Phone')),
                ('dateofadd', models.DateField(auto_now_add=True)),
                ('date_of_update', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('roleid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Roles', verbose_name='RoleID')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
