version: '3.2'

services:
  db:
    restart: always
    image: postgres:10-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"

  web:
    restart: always
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env