version: '3.2'

services:
  db:
    restart: always
    image: postgres:10-alpine
    env_file:
      - .env
    ports:
      - "5431:5431"

  web:
    restart: always
    build: .
    ports:
      - "8800:8800"
    depends_on:
      - db
    env_file:
      - .env