# Generated by Django 2.2.7 on 2019-12-25 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='waiterid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Waiter'),
        ),
        migrations.AddField(
            model_name='mealscount',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Meals', verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='mealscount',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealsid', to='food.Orders'),
        ),
        migrations.AddField(
            model_name='meals',
            name='categoryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.MealCategories', verbose_name='CategoryID'),
        ),
        migrations.AddField(
            model_name='mealcategories',
            name='departmentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Departments', verbose_name='DemartmentID'),
        ),
        migrations.AddField(
            model_name='checks',
            name='mealsid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.MealsCount', verbose_name='Meal'),
        ),
        migrations.AddField(
            model_name='checks',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Orders', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='checks',
            name='servicefee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.ServicePercentage'),
        ),
    ]
