# Generated by Django 2.2.7 on 2019-12-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepercentage',
            name='percentage',
            field=models.FloatField(verbose_name='Percentage'),
        ),
    ]
