# Generated by Django 2.2.7 on 2019-12-03 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='roleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roleid', to='food.Roles', verbose_name='RoleID'),
        ),
    ]
