# Generated by Django 2.2.7 on 2019-12-03 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20191203_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getusertoken',
            name='roleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_user_token', to='food.Roles', verbose_name='RoleID'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='tablename',
            field=models.IntegerField(choices=[('Table #1', 'Table #1'), ('Table #2', 'Table #2'), ('Table #3', 'Table #3'), ('Table #4', 'Table #4'), ('Table #5', 'Table #5')], verbose_name='Number of table'),
        ),
        migrations.AlterField(
            model_name='tables',
            name='name',
            field=models.CharField(choices=[('Table #1', 'Table #1'), ('Table #2', 'Table #2'), ('Table #3', 'Table #3'), ('Table #4', 'Table #4'), ('Table #5', 'Table #5')], max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='roleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='food.Roles', verbose_name='RoleID'),
        ),
    ]
