# Generated by Django 2.2.7 on 2019-12-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20191210_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checks',
            name='totalsum',
        ),
    ]
