# Generated by Django 2.2.7 on 2019-12-10 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_checks_totalsum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealscount',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealsid', to='food.Orders'),
        ),
    ]
